version: '3'

services:

  db:
    build:
      dockerfile: Dockerfile.postgres
      context: "."

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678

    container_name: database

    ports:
      - "3333:3333"

    networks: 
      - banco

networks: 
  banco:
      driver: bridge